version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
  building_scraper:
    build: .
    environment:
      - MONGO_URL=mongodb://db:27017
    volumes:
      - .:/usr/src
    depends_on:
      - db
